### ISSUE TITLE
Fix found: Materials are not set to submeshes correctly

### ISSUE THREAD

**Issue by rpgplayerrobin** [OGRECave/maya-exporter#2]
Materials are not set to the submeshes correctly when exporting them to Ogre.
This is because in newer versions of Ogre you cannot set a material to a submesh if the material does not exist.
Therefore you must make sure the material exists, which I have a working solution for here:

Go into Submesh::createOgreSubmesh.
Right before "pSubmesh->setMaterialName", add this:

std::string tmpMaterialName = m_pMaterial->name().asChar();
if (!Ogre::MaterialManager::getSingleton().getByName(tmpMaterialName))
	Ogre::MaterialManager::getSingleton().create(tmpMaterialName, "General");

**Comment by paroj** [comment]
can you create a pull-request for this? You should be able to do the changes via the web UI with:
https://github.com/OGRECave/maya-exporter/edit/master/src/submesh.cpp

**Comment by rpgplayerrobin** [comment]
Did I do it correctly? :D I am a complete newbie on github.

**Comment by paroj** [comment]
jup. fixed by #3
